### PR TITLE
Add shortcode : [likecoin]

### PR DESCRIPTION
**Pull request by john970473**

### CODE REVIEW

**Comment by williamchong007** [comment]
Thanks for the PR
hmm I think the interface for shortcut handler function should be `($attr, $content, $tag)` instead of `($content)`
I guess I will merge this PR into a feature branch, and do some refactor base on it

**Comment by john970473** [comment]
Thanks. I think it's better to add a LikeCoin widget. Do you want me to help ?

**Comment by williamchong007** [comment]
Sure, what kind of information you imagine this widget would have?

**Comment by john970473** [comment]
Someone asked me how to add LikeCoin to the widget.  I have tried to add the shortcode on the text widget but I failed because "likecoin_add_likebutton()" is just for posts or pages. Therefore, we could change the function and add the button to the widget.

**Comment by john970473** [comment]
At this moment, I could only add Javascript to the widget, but the style of the button looks not so good.
You can see the widget of my blog : [https://www.johntool.com](https://www.johntool.com).
I think the button is too small, and I have to split url and add to link.

**Comment by williamchong007** [comment]
Opened a new issue for discussion https://github.com/likecoin/likecoin-wordpress/issues/56

**Pull request merged**
