### PR TITLE
🔀 Init commit

### PR DESCRIPTION
**Pull request by inDream**
## Done:
- [x] Add meta box in New / Edit Post Page
- [x] Handle version upgrade
- [x] Login with likecoin API
- [x] Update author likecoin id by ajax
- [x] Show widget in template

## Todos:
- [ ] Admin page for author update likecoin id
- [ ] Handle save post without likecoin id

### CODE REVIEW

**Comment by williamchong007** [comment]
since we would need to have some kind of build/babel since js is in ES6
is it possible to use wepack+vue to handle user-facing frontend part of this plugin?

**Comment by inDream** [comment]
@williamchong007 would it pollute global `Vue` namespace and affect other plugins or user template?

**Comment by rickmak** [comment]
I don't know why we need vue here. Webpack already overkill. I think babel will be fine?

**Comment by inDream** [comment]
I think the plugin need some ways to manage client side states.
Currently using style but it's not connivence to add or remove components.

Here is an example using Vue inside plugin:
https://github.com/ianmjones/wp-cron-pixie/tree/vuejs

**Comment by williamchong007** [comment]
@inDream Not sure how would it work, but it probably should has it own `new Vue` then all the magic around its own instance?
@rickmak It would avoid all build/compatibility problems altogether, and at the same time allow easier component sharing and more complex frontend in the future

**Comment by rickmak** [comment]
It's fine for me to use vue.js if setup time is not much concern. Or otherwise, I suggest to stick with current one until phase 2. Phase 1 scope is simple and able to create with plain jQuery.

@williamchong007 too push the development, we may need to setup the daily stand up with you. If you are the sole merger.

**Pull request merged**
